version: '3'

services:
    ws:
        container_name: ws
        image: hoangthanhlam1984/ws-demo:development
        restart: unless-stopped
        ports:
            - "9001:9000"
        volumes:
            - /projects/ws:/www/ws
        networks:
            - demo_network
