version: '3.7'

services:
    ws-demo:
        image: hoangthanhlam1984/ws-demo:development
        restart: unless-stopped
        ports:
            - 9001:9000
            - 80:80
        user: 1000:1000
        working_dir: /var/www/webservice-demo
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.role==worker
