version: '3.7'

services:
    ws-demo:
        image: hoangthanhlam1984/ws-demo:development
        restart: unless-stopped
        user: 1000:1000
        working_dir: /var/www/webservice-demo

    ws-demo-schedule:
        image: hoangthanhlam1984/ws-demo:development
        restart: unless-stopped
        user: 1000:1000
        working_dir: /var/www/webservice-demo
        command: php artisan schedule:rundeploy:
        deploy:
            restart_policy:
                condition: any
                delay: 1m

    ws-demo-queue:
        image: hoangthanhlam1984/ws-demo:development
        restart: unless-stopped
        user: 1000:1000
        working_dir: /var/www/webservice-demo
        command: php artisan queue:work --tries=1