version: '3.7'

services:
    ws-demo:
        image: hoangthanhlam1984/ws-demo:development
        restart: unless-stopped
        ports:
            - 9001:9100
            - 8080:80
        user: 1000:1000
        working_dir: /var/www/webservice-demo
