version: '3.7'

services:
    ws-demo:
        image: hoangthanhlam1984/ws-demo:staging
        restart: unless-stopped
        ports:
            - 9001:9000
            - 80:80
        user: 1000:1000
        working_dir: /var/www/webservice-demo
